### ISSUE TITLE
Website error. Contact admin to have it fixed

### ISSUE THREAD

**Issue by avinkr** [msaad1999/KLiK-SocialMediaWebsite#11]
I am getting login and signup error as **Website error. Contact admin to have it fixed**

reply to us ASAP

**Comment by msaad1999** [comment]
That is a generic error message made for normal users and is not a debug stack trace. Common occurrences of this may be due to database connectivity issues or some errors in the code in case any changes were made.

**Comment by madromas** [comment]
No changes were made, clean install, same error, php 8.1
