### ISSUE TITLE
PHP warnings

### ISSUE THREAD

**Issue by JohnWick0501** [msaad1999/KLiK-SocialMediaWebsite#2]
login.php gives 3 warnings and dashboard gives a mysql warning error.
include 
these are the error:
1. Warning: include_once(dbh.inc.php): failed to open stream: No such file or directory in C:\xampp\htdocs\KLiK-SocialMediaWebsite-master\login.php on line 4

2. Warning: include_once(): Failed opening 'dbh.inc.php' for inclusion (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\KLiK-SocialMediaWebsite-master\login.php on line 4

3. Warning: include(1): failed to open stream: No such file or directory in C:\xampp\htdocs\KLiK-SocialMediaWebsite-master\login.php on line 105

4. Warning: include(): Failed opening '1' for inclusion (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\KLiK-SocialMediaWebsite-master\login.php on line 105

after  login and going to dashboads these are the errors:
1. Warning: include(includes/arrays.php): failed to open stream: No such file or directory in C:\xampp\htdocs\KLiK-SocialMediaWebsite-master\index.php on line 9

2. Warning: include(): Failed opening 'includes/arrays.php' for inclusion (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\KLiK-SocialMediaWebsite-master\index.php on line 9

3. Warning
: mysqli_stmt_bind_param(): Number of variables doesn't match number of parameters in prepared statement in
C:\xampp\htdocs\KLiK-SocialMediaWebsite-master\index.php
on line
116

4. Warning
: mysqli_stmt_bind_param(): Number of variables doesn't match number of parameters in prepared statement in
C:\xampp\htdocs\KLiK-SocialMediaWebsite-master\index.php
on line
177

i have also attached the ss of all the errors.
![capture](https://user-images.githubusercontent.com/47840243/53298272-7badb980-3851-11e9-8a97-c450bc458279.PNG)
![capture1](https://user-images.githubusercontent.com/47840243/53298274-7badb980-3851-11e9-9ab5-c0b1589e6803.PNG)
![capture2](https://user-images.githubusercontent.com/47840243/53298275-7badb980-3851-11e9-8cb8-ca14a092ccab.PNG)
![capture3](https://user-images.githubusercontent.com/47840243/53298276-7c465000-3851-11e9-8a2d-cc2ed56ace47.PNG)
![capture4](https://user-images.githubusercontent.com/47840243/53298277-7c465000-3851-11e9-8682-7093164eb742.PNG)

**Comment by msaad1999** [comment]
> Thank you for bringing our attention to this problem. 

As it turns out, the issues are with the project itself, which somehow escaped debugging in recent tests. We, the developers, have debugged the entire application, fixing all of the problems mentioned here along with others that escaped out notice previously

The bugs have been fixed, and the repository has been updated. You can download the newer version and try implementing that.
