### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by rencontre634** [msaad1999/KLiK-SocialMediaWebsite#7]
Hi congratulations on this good job, I just had a little suggestion
is there no way to put it in multilingual ?

**Comment by msaad1999** [comment]
Apologies for the late response.
This was a very early and simplistic project of mine, so unfortunately in its current shape it doesn't have the scalability to accommodate multiple languages. That would require extensive reworking of the project structure, and incorporation of OOP, which this sadly lacks.
