### ISSUE TITLE
Frozen Dashboard.

### ISSUE THREAD

**Issue by shashi9** [msaad1999/KLiK-SocialMediaWebsite#9]
I am new to hosting site and all. I have tried to host this site using xampp and the site struck at loading index.php when after successful login. 
![Capture](https://user-images.githubusercontent.com/8157065/103435663-bcd63800-4c37-11eb-9be5-8aa758f858e4.PNG)

**Comment by ekck** [comment]
Am experiencing the same issue, how did you handle it?

**Comment by bethropolis** [comment]
It worked fine for me

**Comment by JMcrafter26** [comment]
I know, I am late, but how did you slove this problem?
